openapi: 3.0.1
info:
  title: Default module
  description: ''
  version: 1.0.0
tags: []
paths:
  /admin/spaces/{id}/reject:
    patch:
      summary: adminSpaceReject
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: id
          in: path
          description: ''
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          description: ''
          required: true
          example: Bearer {{access_token}}
          schema:
            type: string
      responses:
        '202':
          description: ''
          headers: {}
      security: []
  /admin/spaces/{id}/approve:
    patch:
      summary: adminSpaceApprove
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: id
          in: path
          description: ''
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          description: ''
          required: false
          example: Bearer {{access_token}}
          schema:
            type: string
      responses:
        '202':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
components:
  schemas: {}
  responses: {}
  securitySchemes: {}
servers: []
security: []
